title: AI News Blog
email: your-email@example.com
description: "A blog with the latest news on Artificial Intelligence."
baseurl: "/ai-news-blog"  # Adjust if using a project site
url: "https://ai-news-tester.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
