name: Update Blog
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Fetch news
        run: python fetch_news.py

      - name: Generate posts
        run: python generate_posts.py

      - name: Prepare deployment
        run: |
          mkdir deploy
          cp -r _posts deploy/
          cp index.md _config.yml deploy/
          rm -f deploy/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy
          keep_files: false
          force_orphan: true
