# .github/workflows/update.yml
name: Update Blog
on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        
    - name: Install dependencies
      run: pip install feedparser requests
      
    - name: Fetch news
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        GNEWS_TOKEN: ${{ secrets.GNEWS_TOKEN }}
      run: python fetch_news.py
      
    - name: Generate posts
      run: python generate_posts.py
      
- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./_posts       # Changed from ./
    destination_dir: ./_posts   # Changed from ./
    keep_files: false
    force_orphan: true
