name: Update Blog
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Fetch news
        run: python fetch_news.py

      - name: Generate posts
        run: python generate_posts.py

      - name: Manually create a test post
        run: |
          mkdir -p _posts
          echo "---
title: 'Test Post'
date: 2025-02-15
source: 'Test Source'
---
This is a test post to check if posts are being displayed correctly." > _posts/2025-02-15-test-post.md

      - name: Print contents of _posts directory
        run: |
          ls -la _posts

      - name: Print contents of each post file
        run: |
          for file in _posts/*.md; do cat "$file"; done

      - name: Print contents of index.md
        run: cat index.md

      - name: Print contents of _config.yml
        run: cat _config.yml

      - name: Prepare deployment
        run: |
          mkdir deploy
          cp -r _posts deploy/
          cp index.md _config.yml deploy/
          rm -f deploy/.nojekyll

      - name: Print deploy directory contents before deploy
        run: |
          ls -la deploy && cat deploy/index.md && cat deploy/_config.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./deploy
          keep_files: false
          force_orphan: true

      - name: Ensure gh-pages directory is clean
        run: |
          rm -rf gh-pages
          mkdir gh-pages

      - name: Clone gh-pages branch and remove .nojekyll
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git clone --single-branch --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          cd gh-pages
          rm -f .nojekyll
          git add .nojekyll
          git commit -m 'Remove .nojekyll'
          git push origin gh-pages

      - name: Print contents of gh-pages branch
        run: |
          cd gh-pages
          ls -la && cat index.md && cat _config.yml && ls -la _posts && for file in _posts/*.md; do cat "$file"; done
